apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gateway
  namespace: ms
  labels:
    app:  gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  gateway
    spec:
      containers:
      - name:  gateway
        image:  toudherth/gateway:1.0           
        ports:
        - containerPort:  8080
          name:  gateway
     

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: ms
spec:
  selector:
    app: gateway-service
  type: NodePort
  ports:
  - name: gateway-service
    port: 8080
    targetPort: 8080
    nodePort: 32470