apiVersion: apps/v1
kind: Deployment
metadata:
  name: agence-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agence
  template:
    metadata:
      labels:
        app: agence
    spec:
      containers:
        - name: agence
          image: toudherth/agence:1.0
          ports:
            - containerPort: 9093
            
---

apiVersion: v1
kind: Service
metadata:
  name: agence-service
spec:
  selector:
    app: agence
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9093
  type: NodePort
