apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidat
  template:
    metadata:
      labels:
        app: candidat
    spec:
      containers:
        - name: candidat
          image: toudherth/candidat:1.0
          ports:
            - containerPort: 9091
            
---

apiVersion: v1
kind: Service
metadata:
  name: candidat-service
spec:
  selector:
    app: candidat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
  type: NodePort
